language: python

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda info -a

install:
  - conda env create --file resources/environment.yml -n test-env
  - conda install -n test-env --yes flake8 nose coveralls
  - source activate test-env
  - pip install -e .

script:
  - source activate test-env
  - nosetests -v mohakw --with-coverage --cover-package=benchutils
  # lint
  - flake8 mohawk/ setup.py

after_success:
  - coveralls
